name: Tests

on:
  push:
    branches:
      - "master"

  pull_request:
    branches:
      - "*"

jobs:
  tests:
    name: Run tests (OS ${{ matrix.os-version }} / OTP ${{ matrix.otp-version }} / Elixir ${{ matrix.elixir-version }} / Gel ${{ matrix.gel-version }})

    strategy:
      matrix:
        os-version:
          - "ubuntu-22.04"

        otp-version:
          - "24.3"
          - "26.0"

        elixir-version:
          - "1.12"
          - "1.13"
          - "1.14"
          - "1.15"
          - "1.16"
          - "1.17"
          - "1.18"

        gel-version:
          - "2.0"
          - "3.0"
          - "4.0"
          - "5.0"
          - "6.0"

        exclude:
          - elixir-version: "1.12"
            otp-version: "26.0"

          - elixir-version: "1.13"
            otp-version: "26.0"

          - elixir-version: "1.14"
            otp-version: "24.3"

          - elixir-version: "1.15"
            otp-version: "24.3"

          - elixir-version: "1.16"
            otp-version: "24.3"

          - elixir-version: "1.17"
            otp-version: "24.3"

          - elixir-version: "1.18"
            otp-version: "24.3"

    runs-on: ${{ matrix.os-version }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Remove non ${{ matrix.gel-version }} Gel version modules and migrations
        env:
          GEL_VERSION: ${{ matrix.gel-version }}
        run: |
          GEL_VERSION=${GEL_VERSION%%.*}

          rm -r "test/support/schema/migrations/"

          for module_file in `ls test/support/schema/`
          do
              module_version=${module_file%.gel}
              module_version=${module_version#v}
              if test ${GEL_VERSION} -lt ${module_version}
              then
                  module_path="test/support/schema/${module_file}"
                  echo "removing ${module_path}"
                  rm ${module_path}
              fi
          done

          echo "GEL_VERSION=${GEL_VERSION}" >> ${GITHUB_ENV}

      - uses: geldata/setup-gel@v1
        with:
          server-version: ${{ matrix.gel-version }}
          instance-name: gel_elixir

      - name: Generate Gel migrations
        run: |
          gel migration create --non-interactive
          gel migrate

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp-version }}
          elixir-version: ${{ matrix.elixir-version }}

      - name: Set up cache
        uses: actions/cache@v4.2.2
        id: cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: tests-${{ matrix.os-version }}-${{ matrix.otp-version }}-${{ matrix.elixir-version }}-${{ hashFiles('mix.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: mix deps.get --only test

      - name: Create requried users
        run: mix gel.roles.setup

      - name: Run tests
        run: mix coveralls

  result:
    name: Tests conclusion

    needs: tests

    runs-on: ubuntu-22.04

    steps:
      - run: "echo 'Completed!'"
